#!/usr/bin/env python3
"""
TITAN-X SoC — GTKWave Save File Generator
Generates .gtkw files for every module with pre-loaded, color-coded, grouped signals.
Run from repository root: python3 generate_gtkw.py
"""
import os

# GTKWave color codes
RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET = 1, 2, 3, 4, 5, 6, 7

def gtkw_header(vcd_file, gtkw_file, tb_name):
    return f"""[*]
[*] TITAN-X SoC — GTKWave Signal Configuration
[*] Auto-generated by generate_gtkw.py
[*]
[dumpfile] "{vcd_file}"
[dumpfile_mtime] "0"
[dumpfile_size] 0
[savefile] "{gtkw_file}"
[timestart] 0
[size] 1920 1080
[pos] -1 -1
*-18.000000
[treeopen] {tb_name}.
[treeopen] {tb_name}.uut.
[sst_width] 280
[signals_width] 350
[sst_expanded] 1
[sst_vpaned_height] 400
"""

def group_start(name):
    return f"@800200\n-{name}\n"

def group_end(name):
    return f"@1001200\n-End {name}\n"

def bit_sig(path, color=None):
    s = ""
    if color:
        s += f"[color] {color}\n"
    s += f"@28\n{path}\n"
    return s

def bus_sig(path, color=None):
    s = ""
    if color:
        s += f"[color] {color}\n"
    s += f"@22\n{path}\n"
    return s

def write_gtkw(filepath, content):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(content)

# ============================================================
# Module definitions: (dir, tb_name, inst, signals_dict)
# inst = DUT instance name (usually 'uut', one uses 'dut')
# ============================================================
MODULES = [
    # ---- COMMON ----
    {
        "dir": "common/cdc_sync",
        "tb": "tb_cdc_sync", "inst": "uut",
        "groups": [
            ("🕐 System Clocks", [
                ("bit", "clk_a", None), ("bit", "clk_b", None), ("bit", "rst_n", None),
            ]),
            ("📊 Data Path", [
                ("bus", "din", BLUE), ("bus", "dout", GREEN),
            ]),
        ]
    },
    {
        "dir": "common/fifo_sync",
        "tb": "tb_fifo_sync", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔀 Control", [
                ("bit", "wr_en", GREEN), ("bit", "rd_en", BLUE),
                ("bit", "full", RED), ("bit", "empty", ORANGE),
            ]),
            ("📊 Data", [("bus", "data_in", BLUE), ("bus", "data_out", GREEN)]),
            ("📈 Status", [("bus", "count", YELLOW)]),
        ]
    },
    {
        "dir": "common/fifo_async",
        "tb": "tb_fifo_async", "inst": "uut",
        "groups": [
            ("🕐 Clocks", [("bit", "wr_clk", None), ("bit", "rd_clk", None), ("bit", "rst_n", None)]),
            ("🔀 Control", [
                ("bit", "wr_en", GREEN), ("bit", "rd_en", BLUE),
                ("bit", "full", RED), ("bit", "empty", ORANGE),
            ]),
            ("📊 Data", [("bus", "wr_data", BLUE), ("bus", "rd_data", GREEN)]),
        ]
    },
    {
        "dir": "common/reset_sync",
        "tb": "tb_reset_sync", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None)]),
            ("🔄 Reset", [("bit", "rst_in", RED), ("bit", "rst_out", GREEN)]),
        ]
    },
    # ---- CPU PIPELINE ----
    {
        "dir": "backend/rv_regfile",
        "tb": "tb_rv_regfile", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📖 Read Port 1", [("bus", "rs1_addr", BLUE), ("bus", "rs1_data", GREEN)]),
            ("📖 Read Port 2", [("bus", "rs2_addr", BLUE), ("bus", "rs2_data", GREEN)]),
            ("✏️ Write Port", [("bus", "rd_addr", ORANGE), ("bus", "rd_data", YELLOW), ("bit", "rd_wen", RED)]),
        ]
    },
    {
        "dir": "backend/rv_csr",
        "tb": "tb_rv_csr", "inst": "dut",  # NOTE: uses 'dut' not 'uut'
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📝 CSR Access", [
                ("bus", "csr_addr", BLUE), ("bus", "csr_wdata", ORANGE),
                ("bus", "csr_rdata", GREEN), ("bit", "csr_wen", RED),
            ]),
            ("🔐 Privilege", [("bus", "priv_mode", YELLOW)]),
            ("⚡ Trap State", [
                ("bus", "mstatus", INDIGO), ("bus", "mepc", BLUE),
                ("bus", "mcause", RED), ("bus", "mtvec", GREEN),
            ]),
            ("🔔 Interrupts", [
                ("bit", "irq_m_ext", RED), ("bit", "irq_m_timer", ORANGE),
                ("bit", "irq_m_soft", YELLOW),
            ]),
        ]
    },
    {
        "dir": "backend/rv_execute",
        "tb": "tb_rv_execute", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔢 ALU", [
                ("bus", "alu_op", YELLOW), ("bus", "operand_a", BLUE),
                ("bus", "operand_b", INDIGO), ("bus", "alu_result", GREEN),
            ]),
            ("🔀 Branch", [("bit", "branch_taken", RED), ("bus", "branch_target", ORANGE)]),
            ("🎛️ Control", [
                ("bit", "valid_in", GREEN), ("bit", "valid_out", BLUE),
                ("bit", "stall", ORANGE), ("bit", "flush", RED),
            ]),
        ]
    },
    {
        "dir": "backend/rv_fpu",
        "tb": "tb_rv_fpu", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Operands", [("bus", "fp_operand_a", BLUE), ("bus", "fp_operand_b", INDIGO)]),
            ("📤 Result", [("bus", "fp_result", GREEN), ("bus", "fp_op", YELLOW)]),
            ("🚩 Flags (NV,DZ,OF,UF,NX)", [("bus", "fflags", RED)]),
            ("🎛️ Control", [("bit", "fp_valid", GREEN), ("bit", "fp_ready", BLUE)]),
        ]
    },
    {
        "dir": "backend/rv_mem",
        "tb": "tb_rv_mem", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("💾 Memory Access", [
                ("bus", "mem_addr", BLUE), ("bus", "mem_wdata", ORANGE),
                ("bus", "mem_rdata", GREEN),
            ]),
            ("🎛️ Control", [
                ("bit", "mem_wen", RED), ("bit", "mem_ren", GREEN),
                ("bus", "mem_size", YELLOW), ("bit", "stall_req", ORANGE),
            ]),
        ]
    },
    {
        "dir": "backend/rv_writeback",
        "tb": "tb_rv_writeback", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("✏️ Writeback", [
                ("bus", "rd_idx", BLUE), ("bus", "rd_data", GREEN), ("bit", "rd_wen", RED),
            ]),
            ("🔀 Source Select", [("bus", "wb_sel", YELLOW)]),
        ]
    },
    {
        "dir": "frontend/rv_fetch",
        "tb": "tb_rv_fetch", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📍 Program Counter", [("bus", "pc", GREEN), ("bus", "pc_next", BLUE)]),
            ("📜 Instruction", [("bus", "inst", YELLOW), ("bit", "inst_valid", GREEN)]),
            ("🎛️ Control", [
                ("bit", "flush", RED), ("bit", "stall", ORANGE),
                ("bus", "branch_target", INDIGO),
            ]),
        ]
    },
    {
        "dir": "frontend/rv_decode",
        "tb": "tb_rv_decode", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📜 Instruction", [("bus", "inst", YELLOW), ("bus", "opcode", ORANGE)]),
            ("🔍 Decode Output", [
                ("bus", "rs1", BLUE), ("bus", "rs2", INDIGO),
                ("bus", "rd", GREEN), ("bus", "imm", VIOLET),
            ]),
            ("🎛️ Control", [
                ("bus", "alu_op", YELLOW), ("bit", "mem_wen", RED),
                ("bit", "reg_wen", GREEN), ("bit", "branch", ORANGE),
            ]),
        ]
    },
    {
        "dir": "frontend/rv_bpu",
        "tb": "tb_rv_bpu", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🎯 Prediction", [
                ("bus", "pc", BLUE), ("bit", "predict_taken", GREEN),
                ("bus", "predict_target", INDIGO),
            ]),
            ("🔄 Update", [
                ("bit", "update_valid", YELLOW), ("bit", "update_taken", ORANGE),
                ("bus", "update_pc", VIOLET),
            ]),
            ("🔧 Internal", [("bit", "btb_hit", GREEN), ("bus", "bht_counter", YELLOW)]),
        ]
    },
    {
        "dir": "frontend/rv_icache",
        "tb": "tb_rv_icache", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Request", [("bus", "addr", BLUE), ("bit", "hit", GREEN), ("bit", "miss", RED)]),
            ("📤 Data", [("bus", "data_out", GREEN)]),
            ("🔄 Refill", [("bit", "refill_valid", YELLOW), ("bus", "refill_data", ORANGE)]),
        ]
    },
    {
        "dir": "backend/rv_dcache",
        "tb": "tb_rv_dcache", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Request", [
                ("bus", "addr", BLUE), ("bit", "hit", GREEN),
                ("bit", "miss", RED), ("bit", "dirty", ORANGE),
            ]),
            ("📊 Data", [("bus", "data_in", BLUE), ("bus", "data_out", GREEN)]),
            ("🔙 Writeback", [
                ("bit", "writeback", YELLOW), ("bus", "wb_addr", ORANGE),
                ("bus", "wb_data", RED),
            ]),
        ]
    },
    # ---- VIRTUAL MEMORY ----
    {
        "dir": "backend/rv_tlb",
        "tb": "tb_rv_tlb", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔍 Lookup", [
                ("bus", "vpn", BLUE), ("bit", "hit", GREEN), ("bit", "miss", RED),
            ]),
            ("🔄 Translation", [("bus", "ppn", GREEN), ("bus", "asid", INDIGO)]),
            ("🎛️ Control", [("bit", "flush", RED), ("bit", "write_en", YELLOW)]),
        ]
    },
    {
        "dir": "backend/rv_ptw",
        "tb": "tb_rv_ptw", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Request", [("bit", "ptw_req", BLUE), ("bus", "ptw_vpn", INDIGO)]),
            ("🚶 Page Walk (Sv39)", [("bus", "ptw_level", YELLOW), ("bus", "ptw_pte", ORANGE)]),
            ("📤 Result", [("bit", "ptw_done", GREEN), ("bit", "page_fault", RED)]),
        ]
    },
    {
        "dir": "backend/rv_mmu",
        "tb": "tb_rv_mmu", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("⚙️ Configuration", [("bus", "satp", INDIGO), ("bus", "priv_mode", YELLOW)]),
            ("🔄 Address Translation", [("bus", "va_in", BLUE), ("bus", "pa_out", GREEN)]),
            ("🚨 Faults", [("bit", "page_fault", RED), ("bit", "access_fault", ORANGE)]),
        ]
    },
    {
        "dir": "backend/rv_pmp",
        "tb": "tb_rv_pmp", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("⚙️ PMP Config", [("bus", "pmpcfg", INDIGO), ("bus", "pmpaddr", BLUE)]),
            ("🔍 Access Check", [("bus", "check_addr", BLUE), ("bus", "check_type", YELLOW)]),
            ("✅ Result", [("bit", "allow", GREEN), ("bit", "deny", RED)]),
        ]
    },
    {
        "dir": "backend/rv_debug",
        "tb": "tb_rv_debug", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔧 Debug Control", [
                ("bit", "halt_req", RED), ("bit", "resume_req", GREEN),
                ("bit", "halted", ORANGE), ("bit", "running", BLUE),
            ]),
            ("📊 Debug State", [("bus", "dpc", GREEN), ("bus", "dcsr", YELLOW)]),
        ]
    },
    {
        "dir": "backend/clint",
        "tb": "tb_clint", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("⏱️ Timer", [("bus", "mtime", BLUE), ("bus", "mtimecmp", INDIGO)]),
            ("🔔 Interrupts", [("bit", "timer_irq", RED), ("bit", "sw_irq", ORANGE)]),
        ]
    },
    {
        "dir": "backend/plic",
        "tb": "tb_plic", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 IRQ Sources", [("bus", "irq_sources", RED)]),
            ("⚖️ Priority", [("bus", "priority", YELLOW), ("bus", "threshold", ORANGE)]),
            ("📤 Output", [("bus", "claim", GREEN), ("bit", "complete", BLUE), ("bit", "ext_irq", RED)]),
        ]
    },
    {
        "dir": "backend/rv_monitor_core",
        "tb": "tb_rv_monitor_core", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🖥️ Execution", [("bus", "pc", GREEN), ("bus", "inst", YELLOW)]),
            ("🎛️ Control", [("bit", "mon_active", BLUE), ("bit", "halt", RED)]),
        ]
    },
    # ---- MEMORY ----
    {
        "dir": "memory/sram_32x64_180nm",
        "tb": "tb_sram_32x64_180nm", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None)]),
            ("💾 Access", [("bus", "addr", BLUE), ("bus", "din", ORANGE), ("bus", "dout", GREEN)]),
            ("🎛️ Control", [("bit", "wen", RED), ("bit", "cen", YELLOW)]),
        ]
    },
    {
        "dir": "memory/sram_512kx8_180nm",
        "tb": "tb_sram_512kx8_180nm", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None)]),
            ("💾 Access", [("bus", "addr", BLUE), ("bus", "din", ORANGE), ("bus", "dout", GREEN)]),
            ("🎛️ Control", [("bit", "wen", RED), ("bit", "cen", YELLOW)]),
        ]
    },
    {
        "dir": "memory/l2_cache_ctrl",
        "tb": "tb_l2_cache_ctrl", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔄 FSM State", [("bus", "state", YELLOW)]),
            ("📊 Cache Events", [
                ("bit", "hit", GREEN), ("bit", "miss", RED),
                ("bit", "evict", ORANGE), ("bit", "writeback", BLUE),
            ]),
            ("📍 Address", [("bus", "addr", INDIGO)]),
        ]
    },
    {
        "dir": "memory/l2_tag_array",
        "tb": "tb_l2_tag_array", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None)]),
            ("🏷️ Tag", [("bus", "tag_in", BLUE), ("bus", "tag_out", GREEN)]),
            ("📊 Status", [("bit", "valid", GREEN), ("bit", "dirty", RED), ("bus", "way_sel", YELLOW)]),
        ]
    },
    {
        "dir": "memory/l2_data_array",
        "tb": "tb_l2_data_array", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None)]),
            ("📊 Data", [("bus", "data_in", BLUE), ("bus", "data_out", GREEN)]),
            ("🎛️ Control", [("bus", "addr", INDIGO), ("bit", "wen", RED)]),
        ]
    },
    {
        "dir": "memory/l2_snoop_filter",
        "tb": "tb_l2_snoop_filter", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔍 Snoop", [
                ("bus", "snoop_addr", BLUE), ("bit", "snoop_hit", GREEN),
                ("bit", "invalidate", RED),
            ]),
            ("🔄 Coherence (MESI)", [("bus", "state", YELLOW)]),
        ]
    },
    {
        "dir": "memory/ddr_phy_if",
        "tb": "tb_ddr_phy_if", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("⏰ DDR Clock", [("bit", "ddr_ck_p", BLUE), ("bit", "ddr_ck_n", INDIGO)]),
            ("🎛️ DDR Control", [
                ("bit", "ddr_cke", GREEN), ("bit", "ddr_cs_n", RED),
                ("bit", "ddr_ras_n", ORANGE), ("bit", "ddr_cas_n", YELLOW),
                ("bit", "ddr_we_n", VIOLET),
            ]),
            ("📊 DDR Data", [
                ("bus", "ddr_dq", GREEN), ("bus", "ddr_dqs_p", BLUE),
                ("bus", "ddr_dqs_n", INDIGO),
            ]),
            ("📍 DDR Address", [
                ("bus", "ddr_addr", BLUE), ("bus", "ddr_ba", YELLOW),
                ("bus", "ddr_bg", ORANGE),
            ]),
        ]
    },
    {
        "dir": "memory/ddr_scheduler",
        "tb": "tb_ddr_scheduler", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📋 Command", [
                ("bit", "cmd_valid", GREEN), ("bus", "cmd_type", YELLOW),
                ("bit", "ready", BLUE),
            ]),
            ("📍 Address", [("bus", "bank", ORANGE), ("bus", "row", BLUE), ("bus", "col", INDIGO)]),
        ]
    },
    # ---- INTERCONNECT ----
    {
        "dir": "interconnect/axi4_to_ahb",
        "tb": "tb_axi4_to_ahb", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📖 AXI Read", [
                ("bit", "axi_arvalid", GREEN), ("bit", "axi_arready", BLUE),
                ("bus", "axi_araddr", INDIGO),
            ]),
            ("✏️ AXI Write", [
                ("bit", "axi_awvalid", GREEN), ("bit", "axi_awready", BLUE),
                ("bus", "axi_awaddr", INDIGO),
            ]),
            ("🔌 AHB", [
                ("bus", "ahb_htrans", YELLOW), ("bit", "ahb_hwrite", ORANGE),
                ("bus", "ahb_haddr", BLUE), ("bus", "ahb_hrdata", GREEN),
            ]),
        ]
    },
    {
        "dir": "interconnect/ahb_to_apb",
        "tb": "tb_ahb_to_apb", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔌 AHB Input", [
                ("bus", "ahb_htrans", YELLOW), ("bit", "ahb_hwrite", ORANGE),
                ("bus", "ahb_haddr", BLUE),
            ]),
            ("🔌 APB Output", [
                ("bit", "apb_psel", GREEN), ("bit", "apb_penable", BLUE),
                ("bit", "apb_pwrite", ORANGE), ("bus", "apb_paddr", INDIGO),
                ("bus", "apb_pwdata", YELLOW), ("bus", "apb_prdata", GREEN),
            ]),
        ]
    },
    {
        "dir": "interconnect/apb_bridge",
        "tb": "tb_apb_bridge", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔌 APB", [
                ("bus", "paddr", BLUE), ("bit", "psel", GREEN),
                ("bit", "penable", YELLOW), ("bit", "pwrite", ORANGE),
                ("bus", "pwdata", INDIGO), ("bus", "prdata", GREEN),
            ]),
        ]
    },
    {
        "dir": "interconnect/axi4_crossbar",
        "tb": "tb_axi4_crossbar", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("✏️ Master 0 Write", [
                ("bit", "m0_awvalid", GREEN), ("bit", "m0_awready", BLUE),
                ("bus", "m0_awaddr", INDIGO),
            ]),
            ("📖 Master 0 Read", [
                ("bit", "m0_arvalid", GREEN), ("bit", "m0_arready", BLUE),
                ("bus", "m0_araddr", INDIGO),
            ]),
            ("🎯 Slave 0", [
                ("bit", "s0_awvalid", GREEN), ("bit", "s0_awready", BLUE),
                ("bit", "s0_arvalid", YELLOW), ("bit", "s0_arready", ORANGE),
            ]),
        ]
    },
    {
        "dir": "interconnect/qos_controller",
        "tb": "tb_qos_controller", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📊 QoS Metrics", [("bus", "bandwidth", BLUE), ("bus", "threshold", YELLOW)]),
            ("⚡ Actions", [
                ("bit", "boost", GREEN), ("bit", "throttle", RED),
                ("bit", "recover", ORANGE),
            ]),
        ]
    },
    {
        "dir": "interconnect/interconnect_mpu",
        "tb": "tb_interconnect_mpu", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔒 Region Config", [("bus", "region_base", BLUE), ("bus", "region_limit", INDIGO)]),
            ("🔍 Access Check", [("bus", "access_addr", BLUE), ("bus", "access_type", YELLOW)]),
            ("✅ Result", [("bit", "grant", GREEN), ("bit", "deny", RED)]),
        ]
    },
    {
        "dir": "interconnect/mmu_arbiter",
        "tb": "tb_mmu_arbiter", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Requests", [("bit", "req_0", BLUE), ("bit", "req_1", INDIGO)]),
            ("📤 Grants", [("bit", "grant_0", GREEN), ("bit", "grant_1", YELLOW)]),
        ]
    },
    # ---- PERIPHERALS ----
    {
        "dir": "peripherals/uart_16550",
        "tb": "tb_uart_16550", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 Serial Lines", [("bit", "uart_tx", YELLOW), ("bit", "uart_rx", GREEN)]),
            ("📝 Registers", [
                ("bus", "thr", ORANGE), ("bus", "rbr", GREEN),
                ("bus", "lsr", BLUE), ("bus", "dlr", INDIGO),
            ]),
            ("🎛️ Control", [
                ("bit", "baud_tick", YELLOW), ("bit", "tx_busy", RED),
                ("bit", "rx_ready", GREEN),
            ]),
        ]
    },
    {
        "dir": "peripherals/can_controller",
        "tb": "tb_can_controller", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 CAN Bus", [("bit", "can_tx", YELLOW), ("bit", "can_rx", GREEN)]),
            ("📋 Frame", [
                ("bus", "arb_field", BLUE), ("bus", "data_field", GREEN),
                ("bus", "crc", ORANGE),
            ]),
        ]
    },
    {
        "dir": "peripherals/i2c_master",
        "tb": "tb_i2c_master", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 I2C Lines", [("bit", "scl", YELLOW), ("bit", "sda", GREEN)]),
            ("🎛️ Control", [
                ("bit", "start", GREEN), ("bit", "stop", RED),
                ("bit", "ack", BLUE), ("bit", "busy", ORANGE),
            ]),
            ("📊 Data", [("bus", "data_in", BLUE), ("bus", "data_out", GREEN)]),
        ]
    },
    {
        "dir": "peripherals/spi_master",
        "tb": "tb_spi_master", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 SPI Lines", [
                ("bit", "sclk", YELLOW), ("bit", "mosi", GREEN),
                ("bit", "miso", BLUE), ("bit", "cs_n", RED),
            ]),
            ("⚙️ Config", [("bit", "cpol", ORANGE), ("bit", "cpha", INDIGO), ("bus", "prescaler", YELLOW)]),
            ("📊 Data", [("bus", "tx_data", ORANGE), ("bus", "rx_data", GREEN)]),
        ]
    },
    {
        "dir": "peripherals/gpio_ctrl",
        "tb": "tb_gpio_ctrl", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📊 GPIO", [
                ("bus", "gpio_dir", BLUE), ("bus", "gpio_out", GREEN),
                ("bus", "gpio_in", INDIGO),
            ]),
            ("🔔 Interrupt", [("bit", "gpio_irq", RED)]),
        ]
    },
    {
        "dir": "peripherals/rtc",
        "tb": "tb_rtc", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None), ("bit", "rtc_clk", YELLOW)]),
            ("⏱️ Counter", [("bus", "counter", BLUE), ("bus", "alarm", INDIGO)]),
            ("🔔 Interrupt", [("bit", "timer_irq", RED)]),
        ]
    },
    {
        "dir": "peripherals/watchdog_timer",
        "tb": "tb_watchdog_timer", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🐕 Watchdog", [("bus", "load_val", BLUE), ("bus", "counter", GREEN)]),
            ("🎛️ Control", [("bit", "enable", GREEN), ("bit", "wdt_reset", RED)]),
        ]
    },
    {
        "dir": "peripherals/trng",
        "tb": "tb_trng", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🎲 Output", [("bus", "random_data", GREEN)]),
            ("📊 Status", [("bit", "entropy_valid", BLUE), ("bit", "health_check", YELLOW)]),
        ]
    },
    {
        "dir": "peripherals/aes_engine",
        "tb": "tb_aes_engine", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔑 Key", [("bus", "key", INDIGO)]),
            ("📊 Data", [("bus", "plaintext", BLUE), ("bus", "ciphertext", GREEN)]),
            ("🎛️ Control", [("bit", "start", GREEN), ("bit", "done", BLUE)]),
        ]
    },
    {
        "dir": "peripherals/sha256_engine",
        "tb": "tb_sha256_engine", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📥 Input", [("bus", "data_in", BLUE)]),
            ("📤 Hash Output", [("bus", "hash_out", GREEN)]),
            ("🎛️ Control", [("bit", "start", GREEN), ("bit", "done", BLUE)]),
        ]
    },
    {
        "dir": "peripherals/gem_ethernet",
        "tb": "tb_gem_ethernet", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📤 GMII TX", [("bus", "gmii_txd", GREEN), ("bit", "tx_en", BLUE), ("bit", "tx_er", RED)]),
            ("📥 GMII RX", [("bus", "gmii_rxd", INDIGO), ("bit", "rx_dv", BLUE), ("bit", "rx_er", RED)]),
            ("📊 Status", [("bit", "crc_valid", GREEN), ("bit", "link_up", BLUE)]),
        ]
    },
    {
        "dir": "peripherals/gem_sgmii_pcs",
        "tb": "tb_gem_sgmii_pcs", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 SGMII", [("bus", "sgmii_txd", GREEN), ("bus", "sgmii_rxd", BLUE)]),
            ("🤝 Autoneg", [("bit", "an_complete", GREEN), ("bit", "link_status", BLUE)]),
        ]
    },
    {
        "dir": "peripherals/pcie_pipe_if",
        "tb": "tb_pcie_pipe_if", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "pipe_clk", None), ("bit", "rst_n", None)]),
            ("📤 PIPE TX", [("bus", "pipe_txdata", GREEN), ("bit", "pipe_txelecidle", YELLOW)]),
            ("📥 PIPE RX", [("bus", "pipe_rxdata", BLUE), ("bus", "pipe_rxstatus", ORANGE)]),
        ]
    },
    {
        "dir": "peripherals/pcie_top",
        "tb": "tb_pcie_top", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📋 TLP", [("bus", "tlp_type", YELLOW), ("bus", "tlp_data", GREEN)]),
            ("💾 DMA", [("bit", "dma_req", BLUE), ("bit", "dma_ack", GREEN)]),
            ("📊 Status", [("bit", "completion_valid", GREEN), ("bit", "link_up", BLUE)]),
        ]
    },
    # ---- SECURITY ----
    {
        "dir": "security/drbg",
        "tb": "tb_drbg", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🌱 Input", [("bus", "seed", INDIGO)]),
            ("📤 Output", [("bus", "random_bits", GREEN)]),
            ("🎛️ Control", [("bit", "generate", GREEN), ("bit", "reseed_req", YELLOW), ("bit", "valid", BLUE)]),
        ]
    },
    {
        "dir": "security/ecdsa_engine",
        "tb": "tb_ecdsa_engine", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔑 Keys", [("bus", "private_key", INDIGO), ("bus", "public_key", BLUE)]),
            ("✍️ Signature", [("bus", "signature_r", GREEN), ("bus", "signature_s", YELLOW)]),
            ("🎛️ Control", [("bit", "start", GREEN), ("bit", "done", BLUE), ("bit", "verify_pass", GREEN)]),
        ]
    },
    {
        "dir": "security/envm_ctrl",
        "tb": "tb_envm_ctrl", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("💾 Access", [("bus", "addr", BLUE), ("bus", "data_out", GREEN)]),
            ("🎛️ Operations", [("bit", "program", ORANGE), ("bit", "erase", RED), ("bit", "busy", YELLOW)]),
        ]
    },
    {
        "dir": "security/secure_boot",
        "tb": "tb_secure_boot", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("🔄 Boot State", [("bus", "boot_state", YELLOW)]),
            ("✅ Verification", [
                ("bit", "hash_match", BLUE), ("bit", "boot_pass", GREEN),
                ("bit", "boot_fail", RED),
            ]),
        ]
    },
    # ---- STORAGE ----
    {
        "dir": "storage/mmc_controller",
        "tb": "tb_mmc_controller", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📋 Command", [("bit", "cmd", YELLOW), ("bus", "cmd_resp", GREEN)]),
            ("📊 Data", [("bus", "data_out", GREEN), ("bus", "data_in", BLUE)]),
            ("📊 Status", [("bit", "card_detect", BLUE), ("bit", "busy", ORANGE)]),
        ]
    },
    {
        "dir": "storage/qspi_controller",
        "tb": "tb_qspi_controller", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📡 QSPI", [("bit", "sclk", YELLOW), ("bit", "cs_n", RED)]),
            ("📊 Data", [("bus", "io", GREEN)]),
            ("⚙️ Mode", [("bit", "quad_mode", BLUE), ("bit", "xip_mode", INDIGO)]),
        ]
    },
    {
        "dir": "storage/usb_otg",
        "tb": "tb_usb_otg", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📊 ULPI Data", [("bus", "ulpi_data", GREEN)]),
            ("🎛️ Control", [
                ("bit", "ulpi_dir", BLUE), ("bit", "ulpi_nxt", YELLOW),
                ("bit", "ulpi_stp", ORANGE),
            ]),
        ]
    },
    # ---- VIDEO ----
    {
        "dir": "video/mipi_csi2_rx",
        "tb": "tb_mipi_csi2_rx", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📊 Data", [("bus", "byte_data", GREEN), ("bus", "data_type", YELLOW)]),
            ("🔄 Sync", [("bit", "line_valid", GREEN), ("bit", "frame_valid", BLUE)]),
        ]
    },
    {
        "dir": "video/isp_pipeline",
        "tb": "tb_isp_pipeline", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("📊 Pixel I/O", [("bus", "pixel_in", BLUE), ("bus", "pixel_out", GREEN)]),
            ("🎨 RGB Channels", [("bus", "r", RED), ("bus", "g", GREEN), ("bus", "b", BLUE)]),
            ("⚙️ Config", [("bit", "demosaic_en", YELLOW), ("bus", "awb_gain", ORANGE)]),
        ]
    },
    {
        "dir": "video/hdmi_ctrl",
        "tb": "tb_hdmi_ctrl", "inst": "uut",
        "groups": [
            ("🕐 System", [
                ("bit", "clk", None), ("bit", "rst_n", None),
                ("bit", "hdmi_clk_pixel", BLUE), ("bit", "hdmi_clk_tmds", INDIGO),
            ]),
            ("📡 TMDS Output", [
                ("bit", "tmds_clk_p", YELLOW), ("bit", "tmds_clk_n", ORANGE),
                ("bus", "tmds_data_p", GREEN), ("bus", "tmds_data_n", BLUE),
            ]),
            ("🖥️ Video Timing", [
                ("bus", "pixel_data", GREEN), ("bit", "hsync", YELLOW),
                ("bit", "vsync", ORANGE), ("bit", "de", BLUE),
            ]),
        ]
    },
    {
        "dir": "video/vdma",
        "tb": "tb_vdma", "inst": "uut",
        "groups": [
            ("🕐 System", [("bit", "clk", None), ("bit", "rst_n", None)]),
            ("💾 DMA Config", [
                ("bus", "src_addr", BLUE), ("bus", "dst_addr", INDIGO),
                ("bus", "xfer_count", YELLOW),
            ]),
            ("🔌 AXI Interface", [
                ("bit", "axi_arvalid", GREEN), ("bit", "axi_arready", BLUE),
                ("bit", "axi_awvalid", YELLOW), ("bit", "axi_awready", ORANGE),
            ]),
            ("📊 Status", [("bit", "dma_done", GREEN), ("bit", "dma_busy", ORANGE)]),
        ]
    },
]


def generate_gtkw_for_module(mod):
    """Generate a .gtkw file for one module."""
    tb = mod["tb"]
    inst = mod["inst"]
    vcd = f"{tb}.vcd"
    gtkw_name = f"{tb}.gtkw"
    gtkw_path = os.path.join(mod["dir"], gtkw_name)
    prefix = f"{tb}.{inst}"

    content = gtkw_header(vcd, gtkw_name, tb)

    for group_name, signals in mod["groups"]:
        content += group_start(group_name)
        for sig_type, sig_name, color in signals:
            full_path = f"{prefix}.{sig_name}"
            if sig_type == "bit":
                content += bit_sig(full_path, color)
            else:
                content += bus_sig(full_path, color)
        content += group_end(group_name)

    content += "\n[pattern_trace] 1\n[pattern_trace] 0\n"

    write_gtkw(gtkw_path, content)
    return gtkw_path


def main():
    print("🔬 TITAN-X SoC — GTKWave Save File Generator")
    print("=" * 50)

    generated = 0
    for mod in MODULES:
        path = generate_gtkw_for_module(mod)
        print(f"  ✅ {path}")
        generated += 1

    print(f"\n{'=' * 50}")
    print(f"✅ Generated {generated} GTKWave save files")
    print(f"\nUsage: gtkwave <vcd_file> <gtkw_file>")
    print(f"Example: cd common/fifo_sync && gtkwave tb_fifo_sync.vcd tb_fifo_sync.gtkw &")


if __name__ == "__main__":
    main()
